version: '3.7'

services:
  server:
    command: ""
    ports:
      - "8000:8000"
    env_file:
      - vars.env
    image: rootcode_fastapi
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    networks:
      - rootcode_net

  db:
    image: "postgres:12.9-alpine3.14"
    volumes:
        - data/postgres:/var/lib/postgresql/data
        - data/postgres_backups:/backups
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres
      - TZ=Europe/Moscow
    # make port public to have opportunity to connect to DB externally
    ports:
      - 5433:5432
    networks:
      - rootcode_net

networks:
  rootcode_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
      com.docker.network.bridge.name: "r_docker_net"
